export const rooms = {
  build: {
    slug: "build",
    title: "Build",
    eyebrow: "THE WORKSHOP",
    welcome: "Bring what wants to become real.",
    signature: "Show us what you're building.",
    identityBody:
      "Every real thing was once an incomplete idea on a table. This is the room where that table lives — cold light, clean surfaces, and the strange quiet of building. Whatever you're making is already real enough to place here.",
    desk: {
      eyebrow: "THE BUILD TABLE",
      heading: "Place your build on the table.",
      tag: "build",
      submitLabel: "Place it on the table",
      confirmation: "Your build is on the table. We'll receive it and route it intentionally.",
      fields: [
        { name: "name",  label: "Your name",   type: "text",  required: true,  top: true },
        { name: "email", label: "Email",        type: "email", required: true,  top: true },
        {
          name: "what_building",
          label: "What are you building?",
          type: "textarea",
          required: false,
        },
        {
          name: "stage",
          label: "What stage is it?",
          type: "select",
          required: false,
          options: ["idea", "building", "launched", "scaling"],
        },
        {
          name: "need_most",
          label: "What do you need most?",
          type: "multiselect",
          required: false,
          options: ["capital", "story", "product", "distribution", "team", "clarity", "partners"],
        },
        { name: "link", label: "Link / deck / demo (optional)", type: "text", required: false },
        {
          name: "looking_for",
          label: "What are you looking for?",
          type: "multiselect",
          required: false,
          options: ["Translation", "Studio", "Fund", "Fellowship", "Partners"],
        },
      ],
    },
  },

  belong: {
    slug: "belong",
    title: "Belong",
    eyebrow: "THE LIVING ROOM",
    welcome: "Come in. The fire's already going.",
    signature: "Come be received.",
    identityBody:
      "This is the room at golden hour — low light, gathered voices, a table that's already set. There's no performance here, nothing to prove. Just the strange relief of being seen without having to shrink.",
    exploration: [
      {
        label: "For",
        title: "Belonging",
        body: "Being received without shrinking. Without earning it first.",
      },
      {
        label: "Happens",
        title: "Gatherings",
        body: "Dinners, fellowship chapters, the kind of evenings that turn into family.",
      },
      {
        label: "Who belongs",
        title: "Anyone seeking it",
        body: "Anyone seeking to be truly received. Meet the family already here.",
        href: "/family",
      },
      {
        label: "Bring",
        title: "Just yourself",
        body: "Your presence is the invitation. That's the whole ask.",
      },
    ],
    desk: {
      eyebrow: "THE GUESTBOOK",
      heading: "Sign the guestbook.",
      tag: "belong",
      submitLabel: "Be received",
      confirmation: "You've been received through Belong. We'll place this intentionally.",
      fields: [
        { name: "name",  label: "Your name", type: "text",  required: true,  top: true },
        { name: "email", label: "Email",      type: "email", required: true,  top: true },
        { name: "city",  label: "City",        type: "text",  required: false, top: true },
        {
          name: "alive",
          label: "What makes you feel alive?",
          type: "textarea",
          required: false,
        },
        {
          name: "room_types",
          label: "What kind of rooms do you belong in?",
          type: "multiselect",
          required: false,
          options: [
            "dinners",
            "friendship",
            "founders",
            "faith/spiritual",
            "creative",
            "local chapter",
            "online room",
            "not sure",
          ],
        },
        {
          name: "seeking",
          label: "What are you seeking right now?",
          type: "textarea",
          required: false,
        },
        {
          name: "invite_preference",
          label: "How would you like to be invited?",
          type: "multiselect",
          required: false,
          options: [
            "gatherings",
            "digital rooms",
            "local chapters",
            "founder–fellowship circles",
          ],
        },
        {
          name: "open_notes",
          label: "Anything we should know?",
          type: "textarea",
          required: false,
        },
      ],
    },
  },
};
