export const rooms = {
  bring: {
    slug: "bring",
    title: "Bring",
    eyebrow: "THE OFFERING TABLE",
    welcome: "There's a seat with your name on it.",
    signature: "Bring who you are.",
    identityBody:
      "Every table has a place already set. The question is never whether there's room — it's whether you'll come with what you actually have. Your gift, your skill, your table, your network, your time. This is where those things find their right home.",
    desk: {
      eyebrow: "THE OFFERING TABLE",
      heading: "Bring who you are.",
      tag: "bring",
      submitLabel: "Set your place",
      confirmation: "Your place is set. We'll find where your gift belongs.",
      fields: [
        { name: "name",  label: "Your name", type: "text",  required: true, top: true },
        { name: "email", label: "Email",      type: "email", required: true, top: true },
        {
          name: "what_bring",
          label: "What do you bring?",
          type: "multiselect",
          required: false,
          options: ["superpower", "skill", "resource", "room", "story", "venue", "talent", "network", "capacity"],
        },
        {
          name: "how_contribute",
          label: "How do you want to contribute?",
          type: "textarea",
          required: false,
        },
        {
          name: "roles",
          label: "How would you like to show up?",
          type: "multiselect",
          required: false,
          options: ["host", "designer", "operator", "writer", "connector", "technologist", "artist", "investor", "venue owner", "chef", "producer"],
        },
      ],
    },
  },

  seed: {
    slug: "seed",
    title: "Seed",
    eyebrow: "PRIVATE",
    welcome: "Some doors only open quietly.",
    signature: "Seed the first rooms.",
    identityBody:
      "The most significant participation happens before the room fills. This is a private door — for those who move with intention, not urgency. No pitches. No decks. A quiet conversation.",
    desk: {
      eyebrow: "PRIVATE",
      heading: "Open a private conversation.",
      tag: "seed",
      submitLabel: "Send privately",
      confirmation: "Received, privately. We'll reach out directly.",
      fields: [
        { name: "name",  label: "Your name", type: "text",  required: true, top: true },
        { name: "email", label: "Email",      type: "email", required: true, top: true },
        {
          name: "interest",
          label: "Nature of interest",
          type: "multiselect",
          required: false,
          options: ["patronage", "sponsorship", "investment", "partnership", "underwriting events", "seeding rooms", "backing the ecosystem"],
        },
        {
          name: "participation_level",
          label: "Level of participation",
          type: "textarea",
          required: false,
        },
        {
          name: "entity",
          label: "You are",
          type: "select",
          required: false,
          options: ["individual", "family office", "fund", "brand", "institution"],
        },
        {
          name: "private_conversation",
          label: "Request a private conversation?",
          type: "select",
          required: false,
          options: ["yes", "no"],
        },
      ],
    },
  },

  partner: {
    slug: "partner",
    title: "Partner",
    eyebrow: "THE EMBASSY",
    welcome: "Every city is a door.",
    signature: "Open a channel between houses.",
    identityBody:
      "HOME enters the world through aligned institutions, venues, and cities. If you hold space — physical, cultural, digital, civic — there may be a natural alignment here. Tell us about your world.",
    desk: {
      eyebrow: "THE EMBASSY",
      heading: "Open a channel.",
      tag: "partner",
      submitLabel: "Open the channel",
      confirmation: "The channel is open. We'll meet you there.",
      fields: [
        { name: "name",   label: "Your name",       type: "text",  required: true,  top: true },
        { name: "org",    label: "Organization",     type: "text",  required: false, top: false },
        { name: "email",  label: "Email",            type: "email", required: true,  top: true },
        { name: "market", label: "City / market",    type: "text",  required: false, top: true },
        {
          name: "org_type",
          label: "Who are you?",
          type: "multiselect",
          required: false,
          options: ["founder", "creator", "venue", "brand", "city", "developer", "institution", "media", "hospitality", "school", "nonprofit", "cultural org"],
        },
        {
          name: "partnership",
          label: "What partnership do you imagine?",
          type: "textarea",
          required: false,
        },
        {
          name: "assets",
          label: "What assets do you hold?",
          type: "textarea",
          required: false,
        },
        {
          name: "seeking",
          label: "What are you seeking from HOME?",
          type: "textarea",
          required: false,
        },
      ],
    },
  },

  build: {
    slug: "build",
    title: "Build",
    eyebrow: "THE WORKSHOP",
    welcome: "Bring what wants to become real.",
    signature: "Show us what you're building.",
    identityBody:
      "Every real thing was once an incomplete idea on a table. This is the room where that table lives — cold light, clean surfaces, and the strange quiet of building. Whatever you're making is already real enough to place here.",
    desk: {
      eyebrow: "THE BUILD TABLE",
      heading: "Place your build on the table.",
      tag: "build",
      submitLabel: "Place it on the table",
      confirmation: "Your build is on the table. We'll receive it and route it intentionally.",
      fields: [
        { name: "name",  label: "Your name",   type: "text",  required: true,  top: true },
        { name: "email", label: "Email",        type: "email", required: true,  top: true },
        {
          name: "what_building",
          label: "What are you building?",
          type: "textarea",
          required: false,
        },
        {
          name: "stage",
          label: "What stage is it?",
          type: "select",
          required: false,
          options: ["idea", "building", "launched", "scaling"],
        },
        {
          name: "need_most",
          label: "What do you need most?",
          type: "multiselect",
          required: false,
          options: ["capital", "story", "product", "distribution", "team", "clarity", "partners"],
        },
        { name: "link", label: "Link / deck / demo (optional)", type: "text", required: false },
        {
          name: "looking_for",
          label: "What are you looking for?",
          type: "multiselect",
          required: false,
          options: ["Translation", "Studio", "Fund", "Fellowship", "Partners"],
        },
      ],
    },
  },

  belong: {
    slug: "belong",
    title: "Belong",
    eyebrow: "THE LIVING ROOM",
    welcome: "Come in. The fire's already going.",
    signature: "Come be received.",
    identityBody:
      "This is the room at golden hour — low light, gathered voices, a table that's already set. There's no performance here, nothing to prove. Just the strange relief of being seen without having to shrink.",
    exploration: [
      {
        label: "For",
        title: "Belonging",
        body: "Being received without shrinking. Without earning it first.",
      },
      {
        label: "Happens",
        title: "Gatherings",
        body: "Dinners, fellowship chapters, the kind of evenings that turn into family.",
      },
      {
        label: "Who belongs",
        title: "Anyone seeking it",
        body: "Anyone seeking to be truly received. Meet the family already here.",
        href: "/family",
      },
      {
        label: "Bring",
        title: "Just yourself",
        body: "Your presence is the invitation. That's the whole ask.",
      },
    ],
    desk: {
      eyebrow: "THE GUESTBOOK",
      heading: "Sign the guestbook.",
      tag: "belong",
      submitLabel: "Be received",
      confirmation: "You've been received through Belong. We'll place this intentionally.",
      fields: [
        { name: "name",  label: "Your name", type: "text",  required: true,  top: true },
        { name: "email", label: "Email",      type: "email", required: true,  top: true },
        { name: "city",  label: "City",        type: "text",  required: false, top: true },
        {
          name: "alive",
          label: "What makes you feel alive?",
          type: "textarea",
          required: false,
        },
        {
          name: "room_types",
          label: "What kind of rooms do you belong in?",
          type: "multiselect",
          required: false,
          options: [
            "dinners",
            "friendship",
            "founders",
            "faith/spiritual",
            "creative",
            "local chapter",
            "online room",
            "not sure",
          ],
        },
        {
          name: "seeking",
          label: "What are you seeking right now?",
          type: "textarea",
          required: false,
        },
        {
          name: "invite_preference",
          label: "How would you like to be invited?",
          type: "multiselect",
          required: false,
          options: [
            "gatherings",
            "digital rooms",
            "local chapters",
            "founder–fellowship circles",
          ],
        },
        {
          name: "open_notes",
          label: "Anything we should know?",
          type: "textarea",
          required: false,
        },
      ],
    },
  },
};
